Traceback (most recent call last):
  File "/opt/psi/4/master/bin/psi4", line 331, in <module>
    exec(content)
  File "<string>", line 18
    ***, THF_optimization
     ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/psi/4/master/bin/psi4", line 348, in <module>
    suspect_lineno = traceback.extract_tb(exc_traceback)[1].lineno - 1  # -1 for 0 indexing
IndexError: list index out of range
kill: sending signal to 1496 failed: No such process
